version: "3.3"
services:
  relay:
    build: .
    environment:
      - DISCORD_TOKEN=discord_token
      - SPY_CHANNELS=[channelid1, channelid2, ...]
      - WEBHOOK_ID=webhook_id
      - WEBHOOK_TOKEN=webhook_secret
    networks:
      - web

networks:
  web:
    external: true
