version: "3.3"
services:
  relay:
    build: .
    environment:
      - DISCORD_TOKEN=discord_token
      - SPY_CHANNELS=[channelid1, channelid2, ...]
      - WEBHOOK_URL=https://discord.com/api/webhooks/WEBHOOK_ID/WEBHOOK_TOKEN
    networks:
      - web

networks:
  web:
    external: false
